### ISSUE TITLE
Adam: Umbrella Ticket

### ISSUE THREAD

**Issue by AdamHolbel** [error404csp/weather#9]
DB and Sign-up Section of the website

- [x] Completed database for login page
- [x] Completed Sign-up part of the website (some errors)
- [x] Completed Login system (Kaila worked on this but user doesn't stay logged in

Current Ticket:
So far I have completed the database and sign-up section of this and for my next ticket I will finish the login section of the website. The sign up section works fairly well with the database but I would also like to add a message that pops ups telling the user that they either successfully logged in or that the user was taken. Currently, it displays it, but it doesn't look great. 

Next Ticket:
- [ ] Finish pop up telling the user they logged in or couldn't. (To make it look better)
- [ ] Finish login portion of the website

[Code](https://github.com/error404csp/weather/commit/f8afe1481c2b35f38792e4d245cf2829b30db25b)
[Runtime](https://70.95.179.189/)
